# C:\VerdictAlign\render.yaml
services:
  - type: web
    name: verdictalign-api
    runtime: python
    repo: https://github.com/Laeba0123/AccurateAndConsistentModel-VerdictAlign
    plan: free
    branch: main
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
